openapi: 3.0.0
info:
  title: 'My first API'
  contact:
    email: support@example.com
  version: 1.0.0
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: 'Autenticação de usuário'
      operationId: AuthLogin
      parameters:
        -
          name: email
          in: query
          description: 'E-mail para autenticação'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha para autenticação'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /admin/auth/login:
    post:
      tags:
        - auth
      summary: 'Autenticação da administração'
      operationId: AuthAdminLogin
      parameters:
        -
          name: email
          in: query
          description: 'E-mail para autenticação'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha para autenticação'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /auth/refresh:
    post:
      tags:
        - auth
      summary: 'Atualiza o token atual do usuário'
      operationId: AuthRefresh
      responses:
        '200':
          description: ...
  /bans:
    get:
      tags:
        - bans
      summary: 'Lista todos os bans até o momento'
      operationId: GetBanList
      responses:
        '200':
          description: ...
    post:
      tags:
        - bans
      summary: 'Cria um novo ban'
      operationId: StoreBan
      parameters:
        -
          name: admin_id
          in: query
          description: 'ID de quem deu o ban'
          required: true
          schema:
            type: string
        -
          name: victim_id
          in: query
          description: 'ID de quem recebeu o ban'
          required: true
          schema:
            type: string
        -
          name: type
          in: query
          description: 'Tipo de ban (ban/mute/kick)'
          required: true
          schema:
            type: string
        -
          name: reason
          in: query
          description: 'Razão do ban'
          required: true
          schema:
            type: string
        -
          name: time
          in: query
          description: 'Duração do ban'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ...
  '/bans/{id}/revoke':
    get:
      tags:
        - bans
      summary: 'Lista todos os bans até o momento'
      operationId: GetBanList
      parameters:
        -
          name: id
          in: path
          description: 'ID do usuário'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /languages:
    get:
      tags:
        - languages
      summary: 'Lista todas as linguagens de programação no projeto'
      operationId: GetLanguages
      responses:
        '200':
          description: ...
  '/languages/{id}':
    get:
      tags:
        - languages
      summary: 'Lista todas as linguagens de programação no projeto'
      operationId: GetLanguages
      parameters:
        -
          name: id
          in: path
          description: 'ID da linguagem'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  '/users/{discord_id}/levelup':
    post:
      tags:
        - users
      summary: 'Mostra as informações de um usuário'
      operationId: GetUser
      parameters:
        -
          name: discord_id
          in: path
          description: 'ID do usuário do Discord'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /tips/development:
    get:
      tags:
        - tips
      summary: 'Lista todas as dicas armazenadas de desenvolvimento'
      operationId: GetDevelopmentTips
      responses:
        '200':
          description: ...
    post:
      tags:
        - tips
      summary: 'Cria uma nova dica para o estudo de programação'
      operationId: StoreDevelopmentTip
      parameters:
        -
          name: tip
          in: query
          description: 'Dica que vai rolar'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  '/tips/development/{id}':
    delete:
      tags:
        - tips
      summary: 'Deleta uma dica de desenvolvimento'
      operationId: DeleteDevelopmentTip
      parameters:
        -
          name: id
          in: path
          description: 'ID da dica'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /tips/english:
    get:
      tags:
        - tips
      summary: 'Lista todas as dicas armazenadas de inglês'
      operationId: GetEnglishTips
      responses:
        '200':
          description: ...
    post:
      tags:
        - tips
      summary: 'Cria uma nova dica para o estudo de inglês'
      operationId: StoreEnglishTop
      parameters:
        -
          name: tip
          in: query
          description: 'Dica que vai rolar'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  '/tips/english/{id}':
    delete:
      tags:
        - tips
      summary: 'Deleta uma dica de desenvolvimento'
      operationId: DeleteEnglishTip
      parameters:
        -
          name: id
          in: path
          description: 'ID da dica'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /users:
    get:
      tags:
        - users
      summary: 'Lista todos os usuários'
      operationId: GetUsers
      parameters:
        -
          name: date
          in: query
          description: 'Data para filtrar'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ...
    post:
      tags:
        - users
      summary: 'Cria um novo usuário'
      operationId: StoreUser
      parameters:
        -
          name: discord_id
          in: query
          description: 'ID do usuário do Discord'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  '/users/{discord_id}':
    get:
      tags:
        - users
      summary: 'Mostra as informações de um usuário'
      operationId: GetUser
      parameters:
        -
          name: discord_id
          in: path
          description: 'ID do usuário do Discord'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
